### ISSUE TITLE
Qt6 module does not compile.

### ISSUE THREAD

**Issue by TheBoctor** [eegorov/qtcurve#1]
![image](https://github.com/eegorov/qtcurve/assets/45834980/5a1c2122-2f1e-4a66-b888-8d969fd079ed)
Every part of this fork builds as expected, but the Makefiles produced by CMake for `qt6` unfortunately stop with this error. It looks as if a bunch of filenames and variables have been concatenated together, somewhere. Following the compile process has proven difficult. I have been unable to find any problems in the new CMake files you added.

Tested on Arch Linux with all-current packages, as well as Debian Stable 12.4. All dependencies are installed, but both environments will yield the same error messages.

**Comment by eegorov** [comment]
@TheBoctor  can you please attach full build log?

**Comment by TheBoctor** [comment]
Thank you for responding, here is the full log output from Konsole.
[qtcurve-build-attempt.txt](https://github.com/eegorov/qtcurve/files/14189948/qtcurve-build-attempt.txt)

**Comment by eegorov** [comment]
@TheBoctor try
current master not suppost build with qt6 now. This need to fix.

But you can to try:

cd qtcurve
git checkout mr_qt6
cd build 
cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DENABLE_QT6=ON -DENABLE_QT5=OFF
make

**Comment by TheBoctor** [comment]
I completely misunderstood the differences between the branches. Switching to the `mr_qt6` branch as you suggested works without problems. Thank you so much for your help. Hopefully, this can eventually be merged.
![image](https://github.com/eegorov/qtcurve/assets/45834980/e91b61ab-5a50-4d94-8ddc-b0b78233feb2)
