### ISSUE TITLE
Wrong colors?

### ISSUE THREAD

**Issue by mdevaev** [eegorov/qtcurve#2]
First of all, big thank you for making this port. I don't understand why this is no longer supported by the upstream, and I'm glad that I can continue to use the theme that I've been used to for ten years.

I built QtCurve from the mr_qt6 branch and it seems to work, but I see a color discrepancy between the Qt5 and Qt6 applications. I can also see the difference in qt6ct. Do you know why this might be the case?

![image](https://github.com/eegorov/qtcurve/assets/416259/85727e92-b104-4ec4-9b23-cc1839ab0b78)

**Comment by eegorov** [comment]
Честно говоря, не знаю, в чем может быть дело. Возможно тема приложений Qt5 переопределяется KDE-средой, а на Qt6 это переопределение не действует
В моем случае все одинаково:
![image](https://github.com/eegorov/qtcurve/assets/776524/dc22e52a-fee9-4aac-8993-53109f9d32c1)

Но я уже сходу и не вспомню, где именно моя цветовая схема задана. Ей уже лет 15, и ее я настраивал еще во времена 4-х кед, и, соответственно, Qt4

**Comment by eegorov** [comment]
Может быть, раз используешь qt6ct, ты также используешь qt5ct
Загляни в ~/.config/qt5ct/colors Может быть надо настройки оттуда портировать в qt6ct

**Comment by mdevaev** [comment]
Очень странные дела. Я попробовал тупо скопировать цвета, и вот что получается, если я выбираю ее в обоих настройщиках:
![image](https://github.com/eegorov/qtcurve/assets/416259/eedd5649-8d8e-490c-81f1-d2e2a3727ab8)

А вот так, если дефолтная:
![image](https://github.com/eegorov/qtcurve/assets/416259/6621bfe4-7904-480a-afd6-afb53d8e59e8)

**Comment by eegorov** [comment]
@mdevaev 
Нашел: цветовую схему я устанавливал через кде-шную панель настроек из файла:
```
$ cat MyColors.colors 
[ColorEffects:Disabled]
Color=238,238,231
ColorAmount=0
ColorEffect=0
ContrastAmount=0.65
ContrastEffect=1
IntensityAmount=0.1
IntensityEffect=2

[ColorEffects:Inactive]
Color=112,111,110
ColorAmount=0.025
ColorEffect=2
ContrastAmount=0.1
ContrastEffect=2
Enable=false
IntensityAmount=0
IntensityEffect=0

[Colors:Button]
BackgroundAlternate=224,223,222
BackgroundNormal=243,243,240
DecorationFocus=43,116,199
DecorationHover=0,192,0
ForegroundActive=255,128,224
ForegroundInactive=136,135,134
ForegroundLink=0,87,174
ForegroundNegative=191,3,3
ForegroundNeutral=176,128,0
ForegroundNormal=20,19,18
ForegroundPositive=0,110,40
ForegroundVisited=100,74,155

[Colors:Selection]
BackgroundAlternate=62,138,204
BackgroundNormal=49,106,197
DecorationFocus=43,116,199
DecorationHover=0,192,0
ForegroundActive=255,128,224
ForegroundInactive=165,193,228
ForegroundLink=0,49,110
ForegroundNegative=156,14,14
ForegroundNeutral=255,221,0
ForegroundNormal=255,255,255
ForegroundPositive=128,255,128
ForegroundVisited=69,40,134

[Colors:Tooltip]
BackgroundAlternate=196,224,255
BackgroundNormal=254,254,226
DecorationFocus=43,116,199
DecorationHover=0,192,0
ForegroundActive=255,128,224
ForegroundInactive=96,112,128
ForegroundLink=0,87,174
ForegroundNegative=191,3,3
ForegroundNeutral=176,128,0
ForegroundNormal=20,19,18
ForegroundPositive=0,110,40
ForegroundVisited=100,74,155

[Colors:View]
BackgroundAlternate=248,247,246
BackgroundNormal=255,255,255
DecorationFocus=43,116,199
DecorationHover=0,192,0
ForegroundActive=255,128,224
ForegroundInactive=136,135,134
ForegroundLink=0,87,174
ForegroundNegative=191,3,3
ForegroundNeutral=176,128,0
ForegroundNormal=20,19,18
ForegroundPositive=0,110,40
ForegroundVisited=100,74,155

[Colors:Window]
BackgroundAlternate=218,217,216
BackgroundNormal=239,239,231
DecorationFocus=43,116,199
DecorationHover=0,192,0
ForegroundActive=255,128,224
ForegroundInactive=136,135,134
ForegroundLink=0,87,174
ForegroundNegative=191,3,3
ForegroundNeutral=176,128,0
ForegroundNormal=20,19,18
ForegroundPositive=0,110,40
ForegroundVisited=100,74,155

[General]
ColorScheme=my-colors
Name=my-colors
shadeSortColumn=true

[KDE]
contrast=7

[WM]
activeBackground=0,99,249
activeForeground=255,255,255
inactiveBackground=123,153,225
inactiveForeground=20,19,18
```
При этом, если я меняю тему, сразу же перерисовываются все окна: что Qt6, что Qt5

**Comment by mdevaev** [comment]
Я попробую покрутить это и отпишусь, спасибо.

**Comment by mdevaev** [comment]
В итоге я просто пересоздал палитру в qt5ct, скопировал ее в qt6ct и все заработало.

Кстати, вы будете еще пытаться достучаться до KDE-шников, чтобы они приняли патчи? Или просто планируете поддерживать свой форк? Или не особо планируете :)

**Comment by eegorov** [comment]
Ну и отлично. Насколько я понимаю, qt5ct/qt6ct  - это прокси тема, которая работает, в данном случае, поверх qtcurve, переопределяя, в данном случае, палитру.

Что касается апстрима: а как мне из заставлять? :) Я сделал для себя, так как мне это интересно, поделился. Это все, что я могу сделать...

**Comment by mdevaev** [comment]
Да ну не заставлять, зачем так сразу. Просто текущий мейнтейнер пропал уже как пару лет. Можно попробовать связаться с вышестоящими координаторами, чтобы они сделали мейнтейнером вас, например. Ну, если вам хочется, конечно.

**Comment by mdevaev** [comment]
Я так понимаю, можно просто написать в рассылку: [kde-devel@kde.org](mailto:kde-devel@kde.org)

**Comment by eegorov** [comment]
https://invent.kde.org/system/qtcurve/-/issues/2

**Comment by eegorov** [comment]
мейнтейнером - не потяну....

**Comment by mdevaev** [comment]
Штош, значит буду вашу ветку отсюда собирать. Положу в арчевский аур пакетик.

**Comment by mdevaev** [comment]
Хорошие новости. Я смог связаться с мейнтейнером, он сказал, что примет ваши патчи. Он просто не получал уведомлений о проекте и уже начал понемногу делать порт на Qt6 сам, но рад, что вы уже сделали всю работу %)

**Comment by eegorov** [comment]
Это радует! Спасибо за активность. Будем ждать апстрим. На этой радостной ноте ишью закрываю.
